# Generated by Django 5.0.4 on 2024-04-15 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoruseSchedules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('instractor', models.CharField(default='', max_length=30)),
                ('capacity', models.IntegerField(default=0)),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.coruseschedules')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='crud.courses')),
                ('course_prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='crud.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='prerequisites',
            field=models.ManyToManyField(through='crud.Prerequisties', to='crud.courses'),
        ),
        migrations.CreateModel(
            name='studentsReg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.student')),
            ],
        ),
    ]
