# Generated by Django 5.0.4 on 2024-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_coruseschedules_rename_name_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
