# Generated by Django 4.2.11 on 2024-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_user',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
