# Generated by Django 4.2.11 on 2024-04-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_student_fullname_alter_student_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(default='No Name Provided', max_length=90),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_user',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
