# Generated by Django 4.2.11 on 2024-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_student_fullname_alter_student_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
