# Generated by Django 4.2.11 on 2024-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='avatars/'),
        ),
    ]
