# Generated by Django 4.2.11 on 2024-04-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
