# Generated by Django 4.2.11 on 2024-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
    ]
