# Generated by Django 4.2.11 on 2024-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coruseschedules',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='coruseschedules',
            unique_together={('days', 'start_time', 'end_time', 'room_no')},
        ),
    ]
