# Generated by Django 4.2.11 on 2024-05-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_coruseschedules_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.coruseschedules', unique=True),
        ),
    ]
