# Generated by Django 4.2.11 on 2024-05-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_alter_courses_schedule_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coruseschedules',
            unique_together=set(),
        ),
    ]
