# Generated by Django 4.2.11 on 2024-05-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_alter_coruseschedules_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coruseschedules',
            unique_together={('days', 'start_time', 'end_time', 'room_no')},
        ),
    ]
