# Generated by Django 4.2.11 on 2024-05-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_alter_coruseschedules_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coruseschedules',
            name='days',
            field=models.CharField(choices=[('Monday - Wensday', 'Monday - Wensday'), ('Sunday-Tuesday-Thursday', 'Sunday-Tuesday-Thursday')], default='Monday - Wensday', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.coruseschedules'),
        ),
    ]
