# Generated by Django 4.2.11 on 2024-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_alter_courses_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='defult.png', null=True, upload_to='avatars/'),
        ),
    ]
